from PySide6.QtCore import *

fallbackValues = {
    "icon": "richspan_icon.ico",
    "fontFamily": "Segoe UI",
    "fontSize": 9,
    "bold": False,
    "italic": False,    
    "underline": False,
    "contentAlign": Qt.AlignmentFlag.AlignLeft,
    "contentColor": "#FFFFFF",
    "contentBackgroundColor": "transparent",
    "windowScale": None,
    "defaultDirectory": None,
    "fileName": None,
    "content": None,
    "isSaved": None,
    "scrollPosition": None,
    "appTheme": "light",
    "appLanguage": "1252",
    "adaptiveResponse": 1,
    "readFilter": "General File (*.rsdoc *.docx);;HTML (*.html);;Text (*.txt);;Key-Value (*.ini);;LOG (*.log);;JavaScript Object Notation (*.json);;Extensible Markup Language (*.xml);;Javascript (*.js);;Cascading Style Sheets (*.css);;Structured Query Language (*.sql);;Markdown (*.md)",
    "writeFilter": "RichSpan Document (*.rsdoc);;HTML (*.html);;Text (*.txt);;Key-Value (*.ini);;LOG (*.log);;JavaScript Object Notation (*.json);;Extensible Markup Language (*.xml);;Javascript (*.js);;Cascading Style Sheets (*.css);;Structured Query Language (*.sql);;Markdown (*.md)",
    "mediaFilter": "General (*.png *.jpg *.jpeg *.bmp);;Animation (*.gif)",
}


# Locale ID (LCID)
languages = {
    "1252": "English",
    "1031": "Deutsch",
    "1034": "Español",
    "1055": "Türkçe",
    "1068": "Azərbaycanca",
    "1091": "Uzbek",
    "2052": "中文",  # Chinese
    "1042": "한국어",  # Korean
    "1041": "日本語",  # Japanese
    "1025": "العربية",  # Saudi Arabia
    "1049": "Русский",  # Russia
    "1036": "Français",
    "1032": "Ελληνικά",  # Greek
}

translations = {
    "1252": {
        "new": "New",
        "open": "Open",
        "save": "Save",
        "save_as": "Save As",
        "print": "Print",
        "exit": "Exit",
        "file": "File",
        "interface": "Interface",
        "ui": "UI",
        "format": "Format",
        "alignment": "Alignment",
        "color": "Color",
        "multimedia": "Multimedia",
        "darklight": "Dark/Light",
        "darklight_message": "Change theme",
        "edit": "Edit",
        "view": "View",
        "viewmode": "View Mode",
        "viewmode_message": "Change view mode",
        "help": "Help",
        "help_message": "Help",
        "help_shortcut": "Shortcuts",
        "help_description": "Description",
        "about": "About",
        "new": "New",
        "new_message": "New document",
        "open": "Open",
        "open_message": "Open document",
        "save": "Save",
        "save_message": "Save document",
        "save_as": "Save As",
        "save_as_message": "Save document as",
        "print": "Print",
        "print_message": "Print document",
        "find": "Find",
        "find_message": "Find text",
        "replace": "Replace",
        "replace_message": "Replace text",
        "undo": "Undo",
        "undo_message": "Undo action",
        "redo": "Redo",
        "redo_message": "Redo action",
        "right": "Right",
        "right_message": "Right align text",
        "center": "Center",
        "center_message": "Center align text",
        "left": "Left",
        "left_message": "Left align text",
        "justify": "Justify",
        "justify_message": "Justify text",
        "font": "Font",
        "font_message": "Change font",
        "font_size": "Font Size",
        "font_size_message": "Change font size",
        "font_color": "Font Color",
        "font_color_message": "Change font color",
        "contentBackgroundColor": "Background Color",
        "contentBackgroundColor_message": "Change background color",
        "bold": "Bold",
        "bold_message": "Bold text",
        "italic": "Italic",
        "italic_message": "Italic text",
        "underline": "Underline",
        "underline_message": "Underline text",
        "inc_font_message": "Increase font size",
        "dec_font_message": "Decrease font size",
        "image": "Image",
        "image_message": "Insert image",
        "find": "Find",
        "replace": "Replace",
        "find": "Find",
        "untitled": "Untitled",
        "statistic": "Statistic",
        "statistic_message_1": "Lines: {0}",
        "statistic_message_2": "Words: {0}",
        "statistic_message_3": "Characters: {0}",
        "statistic_message_4": "Pages: {0}",
        "analysis": "Analysis",
        "analysis_message_1": "Average Word: {0}",
        "analysis_message_2": "Average Line: {0}",
        "analysis_message_3": "Uppercase: {0}",
        "analysis_message_4": "Lowercase: {0}",
        "analysis_message_5": "Language: {0}",
        "exit": "Exit",
        "exit_message": "Are you sure you want to exit?",
        "cancel": "Cancel",
        "rsdoc": "RichSpan Document",
        "connection_verified": "Connection verified",
        "connection_denied": "Connection denied",
        "logout": "Logout",
        "sync_settings": "Sync Settings",
        "welcome-title": "Welcome — RichSpan",
        "intro": "Login or register with <b>BG Ecosystem</b> account to continue.",
        "wrong_password": "Wrong password",
        "no_account": "You don't have an account.",
        "email": "Email",
        "password": "Password",
        "login": "Login",
        "register": "Register",
        "error": "Error",
        "fill_all": "Please fill all fields.",
        "login_success": "Login successful, redirecting...",
        "wrong_credentials": "Wrong credentials",
        "register_success": "Registration successful, please login.",
        "already_registered": "Already registered",
        "invalid_email": "Invalid email",
        "bullet": "Bullet",
        "numbered": "Numbered",
        "account": "Account",
        "list": "List",
        "powersaver": "Power Saver",
        "powersaver_message": "Hybrid (Ultra/Standard) power saver",
    },
    "1055": {
        "new": "Yeni",
        "open": "Aç",
        "save": "Kaydet",
        "save_as": "Farklı Kaydet",
        "print": "Yazdır",
        "exit": "Çıkış",
        "file": "Dosya",
        "interface": "Arayüz",
        "ui": "Arayüz",
        "format": "Biçim",
        "alignment": "Hizalama",
        "color": "Renk",
        "multimedia": "Multimedya",
        "darklight": "Karanlık/Aydınlık",
        "darklight_message": "Tema değiştir",
        "edit": "Düzenle",
        "view": "Görünüm",
        "viewmode": "Görünüm Modu",
        "viewmode_message": "Görünüm modunu değiştir",
        "multimedia": "Multimedya",
        "help": "Yardım",
        "help_message": "Yardım",
        "help_shortcut": "Kısayollar",
        "help_description": "Açıklama",
        "about": "Hakkında",
        "new": "Yeni",
        "new_message": "Yeni belge",
        "open": "Aç",
        "open_message": "Belge aç",
        "save": "Kaydet",
        "save_message": "Belgeyi kaydet",
        "save_as": "Farklı Kaydet",
        "save_as_message": "Belgeyi farklı kaydet",
        "print": "Yazdır",
        "print_message": "Belgeyi yazdır",
        "find": "Bul",
        "find_message": "Metin bul",
        "replace": "Değiştir",
        "replace_message": "Metin değiştir",
        "undo": "Geri Al",
        "undo_message": "Geri al",
        "redo": "İleri Al",
        "redo_message": "İleri al",
        "right": "Sağa Hizala",
        "right_message": "Metni sağa hizala",
        "center": "Ortala",
        "center_message": "Metni ortala",
        "left": "Sola Hizala",
        "left_message": "Metni sola hizala",
        "justify": "Yasla",
        "justify_message": "Metni yasla",
        "font": "Yazı Tipi",
        "font_message": "Yazı tipini değiştir",
        "font_size": "Yazı Tipi Boyutu",
        "font_size_message": "Yazı tipi boyutunu değiştir",
        "font_color": "Yazı Tipi Rengi",
        "font_color_message": "Yazı tipi rengini değiştir",
        "contentBackgroundColor": "Arkaplan Rengi",
        "contentBackgroundColor_message": "Arkaplan rengini değiştir",
        "bold": "Kalın",
        "bold_message": "Metni kalın yap",
        "italic": "İtalik",
        "italic_message": "Metni italik yap",
        "underline": "Altı Çizili",
        "underline_message": "Metni altı çizili yap",
        "inc_font_message": "Yazı tipi boyutunu büyüt",
        "dec_font_message": "Yazı tipi boyutunu küçült",
        "image": "Resim",
        "image_message": "Resim ekle",
        "find": "Bul",
        "replace": "Değiştir",
        "find": "Bul",
        "untitled": "Başlıksız",
        "statistic": "İstatistik",
        "statistic_message_1": "Satır: {0}",
        "statistic_message_2": "Kelime: {0}",
        "statistic_message_3": "Karakter: {0}",
        "statistic_message_4": "Sayfa: {0}",
        "analysis": "Analiz",
        "analysis_message_1": "Ortalama Kelime: {0}",
        "analysis_message_2": "Ortalama Satır: {0}",
        "analysis_message_3": "Büyük Harf: {0}",
        "analysis_message_4": "Küçük Harf: {0}",
        "analysis_message_5": "Dil: {0}",
        "exit": "Çıkış",
        "exit_message": "Çıkmak istediğinize emin misiniz?",
        "cancel": "İptal",
        "rsdoc": "RichSpan Belgesi",
        "connection_verified": "Bağlantı doğrulandı",
        "connection_denied": "Bağlantı reddedildi",
        "logout": "Çıkış Yap",
        "sync_settings": "Ayarları Senkronize Et",
        "welcome-title": "Hoşgeldiniz — RichSpan",
        "intro": "Devam etmek için <b>BG Ecosystem</b> hesabınızla giriş yapın veya kaydolun.",
        "wrong_password": "Yanlış şifre",
        "no_account": "Hesabınız bulunmamaktadır.",
        "email": "E-posta",
        "password": "Şifre",
        "login": "Giriş Yap",
        "register": "Kayıt Ol",
        "error": "Hata",
        "fill_all": "Lütfen tüm alanları doldurun.",
        "login_success": "Giriş başarılı, yönlendiriliyor...",
        "wrong_credentials": "Yanlış kimlik bilgileri",
        "register_success": "Kayıt başarılı, lütfen giriş yapın.",
        "already_registered": "Zaten kayıtlı",
        "invalid_email": "Geçersiz e-posta",
        "bullet": "Madde",
        "numbered": "Numaralandırılmış",
        "account": "Hesap",
        "list": "Liste",
        "powersaver": "Güç Tasarrufu",
        "powersaver_message": "Hibrit (Ultra/Standart) güç tasarrufu.",
    },
    "1068": {
        "new": "Yeni",
        "open": "Aç",
        "save": "Kaydet",
        "save_as": "Fərqli Olaraq Yadda Saxla",
        "print": "Çap Et",
        "exit": "Çıxış",
        "file": "Fayl",
        "interface": "İnterfeys",
        "ui": "UI",
        "format": "Format",
        "alignment": "Hiza",
        "color": "Rəng",
        "multimedia": "Multimedia",
        "darklight": "Tünd/Aydınlıq",
        "darklight_message": "Mövzu dəyiş",
        "edit": "Dəyiş",
        "view": "Görünüş",
        "viewmode": "Görünüş Modu",
        "viewmode_message": "Görünüş rejimini dəyiş",
        "multimedia": "Multimedia",
        "help": "Kömək",
        "help_message": "Kömək",
        "help_shortcut": "Qısayollar",
        "help_description": "Açıqlama",
        "about": "Haqqında",
        "new": "Yeni",
        "new_message": "Yeni sənəd",
        "open": "Aç",
        "open_message": "Sənədi aç",
        "save": "Saxla",
        "save_message": "Sənədi saxla",
        "save_as": "Fərqli Olaraq Saxla",
        "save_as_message": "Sənədi fərqli şəkildə saxla",
        "print": "Çap Et",
        "print_message": "Sənədi çap et",
        "find": "Tap",
        "find_message": "Mətn tap",
        "replace": "Əvəzlə",
        "replace_message": "Mətni əvəzlə",
        "undo": "Geri Al",
        "undo_message": "Geri al",
        "redo": "İrəli Al",
        "redo_message": "İrəli al",
        "right": "Sağa Doğru",
        "right_message": "Mətni sağa doğru",
        "center": "Ortası",
        "center_message": "Mətni mərkəzlə",
        "left": "Sola Doğru",
        "left_message": "Mətni sola doğru",
        "justify": "Doğrula",
        "justify_message": "Mətni doğrula",
        "font": "Yazı Tipi",
        "font_message": "Yazı tipini dəyiş",
        "font_size": "Yazı Tipi Ölçüsü",
        "font_size_message": "Yazı tipini ölçüsünü dəyiş",
        "font_color": "Yazı Tipi Rəngi",
        "font_color_message": "Yazı tipini rəngini dəyiş",
        "contentBackgroundColor": "Arxa Plan Rəngi",
        "contentBackgroundColor_message": "Arxa plan rəngini dəyiş",
        "bold": "Qalın",
        "bold_message": "Mətni qalınlaşdır",
        "italic": "İtalik",
        "italic_message": "Mətni italikləşdir",
        "underline": "Altı Xəttli",
        "underline_message": "Mətni altı xəttlə",
        "inc_font_message": "Yazı tipi ölçüsünü artır",
        "dec_font_message": "Yazı tipi ölçüsünü azalt",
        "image": "Şəkil",
        "image_message": "Şəkil əlavə et",
        "find": "Tap",
        "replace": "Əvəzlə",
        "find": "Tap",
        "untitled": "Başlıqsız",
        "statistic": "Statistika",
        "statistic_message_1": "Sətrlər: {0}",
        "statistic_message_2": "Sözlər: {0}",
        "statistic_message_3": "Hərflər: {0}",
        "statistic_message_4": "Səhifələr: {0}",
        "analysis": "Təhlil",
        "analysis_message_1": "Orta Söz: {0}",
        "analysis_message_2": "Orta Sətir: {0}",
        "analysis_message_3": "Böyük Hərf: {0}",
        "analysis_message_4": "Kiçik Hərf: {0}",
        "analysis_message_5": "Dil: {0}",
        "exit": "Çıxış",
        "exit_message": "Həqiqətən çıxmaq istəyirsiniz?",
        "cancel": "İmtina Et",
        "rsdoc": "RichSpan Sənədi",
        "connection_verified": "Bağlantı doğrulandı",
        "connection_denied": "Bağlantı reddedildi",
        "logout": "Çıxış Et",
        "sync_settings": "Ayarları Senkronize Et",
        "welcome-title": "Xoş Gəlmisiniz — RichSpan",
        "intro": "Davam etmək üçün <b>BG Ecosystem</b> hesabınızla daxil olun və ya qeydiyyatdan keçin.",
        "wrong_password": "Yanlış şifrə",
        "no_account": "Hesabınız yoxdur.",
        "email": "E-poçt",
        "password": "Şifrə",
        "login": "Giriş Et",
        "register": "Qeydiyyatdan Keç",
        "error": "Xəta",
        "fill_all": "Xahiş olunur bütün xanaları doldurun.",
        "login_success": "Giriş uğurlu, yönləndirilir...",
        "wrong_credentials": "Yanlış kimlik məlumatları",
        "register_success": "Qeydiyyat uğurlu, xahiş olunur giriş edin.",
        "already_registered": "Artıq qeydiyyatdan keçilib",
        "invalid_email": "Yanlış e-poçt",
        "bullet": "Nöqtə",
        "numbered": "Nömrələndirilmiş",
        "account": "Hesab",
        "list": "Siyahı",
        "powersaver": "Enerji qənaəti",
        "powersaver_message": "Hibrid (Ultra/Standart) enerji qənaəti",
    },
    "1031": {
        "new": "Neu",
        "open": "Öffnen",
        "save": "Speichern",
        "save_as": "Speichern als",
        "print": "Drucken",
        "exit": "Beenden",
        "file": "Datei",
        "interface": "Schnittstelle",
        "ui": "UI",
        "format": "Format",
        "alignment": "Ausrichtung",
        "color": "Farbe",
        "multimedia": "Multimedia",
        "darklight": "Dunkel/Licht",
        "darklight_message": "Thema ändern",
        "edit": "Bearbeiten",
        "view": "Ansicht",
        "viewmode": "Ansichtsmodus",
        "viewmode_message": "Ansichtsmodus ändern",
        "multimedia": "Multimedia",
        "help": "Hilfe",
        "help_message": "Hilfe",
        "help_shortcut": "Verknüpfungen",
        "help_description": "Beschreibung",
        "about": "Über",
        "new": "Neu",
        "new_message": "Neues Dokument",
        "open": "Öffnen",
        "open_message": "Dokument öffnen",
        "save": "Speichern",
        "save_message": "Dokument speichern",
        "save_as": "Speichern als",
        "save_as_message": "Dokument anders speichern",
        "print": "Drucken",
        "print_message": "Dokument drucken",
        "find": "Suchen",
        "find_message": "Text finden",
        "replace": "Ersetzen",
        "replace_message": "Text ersetzen",
        "undo": "Rückgängig",
        "undo_message": "Rückgängig machen",
        "redo": "Wiederholen",
        "redo_message": "Wiederholen",
        "right": "Rechts",
        "right_message": "Text rechts ausrichten",
        "center": "Zentriert",
        "center_message": "Text zentrieren",
        "left": "Links",
        "left_message": "Text links ausrichten",
        "justify": "Ausrichten",
        "justify_message": "Text ausrichten",
        "font": "Schriftart",
        "font_message": "Schriftart ändern",
        "font_size": "Schriftgröße",
        "font_size_message": "Schriftgröße ändern",
        "font_color": "Schriftfarbe",
        "font_color_message": "Schriftfarbe ändern",
        "contentBackgroundColor": "Hintergrundfarbe",
        "contentBackgroundColor_message": "Hintergrundfarbe ändern",
        "bold": "Fett",
        "bold_message": "Text fett machen",
        "italic": "Kursiv",
        "italic_message": "Text kursiv machen",
        "underline": "Unterstrichen",
        "underline_message": "Text unterstreichen",
        "inc_font_message": "Schriftgröße erhöhen",
        "dec_font_message": "Schriftgröße verringern",
        "image": "Bild",
        "image_message": "Bild einfügen",
        "find": "Suchen",
        "replace": "Ersetzen",
        "find": "Suchen",
        "untitled": "Ohne Titel",
        "statistic": "Statistik",
        "statistic_message_1": "Zeilen: {0}",
        "statistic_message_2": "Wörter: {0}",
        "statistic_message_3": "Zeichen: {0}",
        "statistic_message_4": "Seiten: {0}",
        "analysis": "Analyse",
        "analysis_message_1": "Durchschnittliches Wort: {0}",
        "analysis_message_2": "Durchschnittliche Zeile: {0}",
        "analysis_message_3": "Großbuchstaben: {0}",
        "analysis_message_4": "Kleinbuchstaben: {0}",
        "analysis_message_5": "Sprache: {0}",
        "exit": "Beenden",
        "exit_message": "Möchten Sie wirklich beenden?",
        "cancel": "Abbrechen",
        "rsdoc": "RichSpan-Dokument",
        "connection_verified": "Verbindung verifiziert",
        "connection_denied": "Verbindung verweigert",
        "logout": "Ausloggen",
        "sync_settings": "Einstellungen synchronisieren",
        "welcome-title": "Willkommen — RichSpan",
        "intro": "Melden Sie sich mit Ihrem <b>BG Ecosystem</b>-Konto an oder registrieren Sie sich, um fortzufahren.",
        "wrong_password": "Falsches Passwort",
        "no_account": "Sie haben kein Konto.",
        "email": "E-Mail",
        "password": "Passwort",
        "login": "Anmelden",
        "register": "Registrieren",
        "error": "Fehler",
        "fill_all": "Bitte füllen Sie alle Felder aus.",
        "login_success": "Anmeldung erfolgreich, Weiterleitung...",
        "wrong_credentials": "Falsche Anmeldedaten",
        "register_success": "Registrierung erfolgreich, bitte anmelden.",
        "already_registered": "Bereits registriert",
        "invalid_email": "Ungültige E-Mail",
        "bullet": "Punkt",
        "numbered": "Nummeriert",
        "account": "Konto",
        "list": "Liste",
        "powersaver": "Energiesparmodus",
        "powersaver_message": "Hybrid (Ultra/Standard) Energiesparmodus",
    },
    "1034": {
        "new": "Nuevo",
        "open": "Abrir",
        "save": "Guardar",
        "save_as": "Guardar como",
        "print": "Imprimir",
        "exit": "Salir",
        "file": "Archivo",
        "interface": "Interfaz",
        "ui": "UI",
        "format": "Formato",
        "alignment": "Alineación",
        "color": "Color",
        "multimedia": "Multimedia",
        "darklight": "Oscuro/Claro",
        "darklight_message": "Cambiar tema",
        "edit": "Editar",
        "view": "Ver",
        "viewmode": "Modo de vista",
        "viewmode_message": "Cambiar modo de vista",
        "help": "Ayuda",
        "help_message": "Ayuda",
        "help_shortcut": "Atajos",
        "help_description": "Descripción",
        "about": "Acerca de",
        "new": "Nuevo",
        "new_message": "Nuevo documento",
        "open": "Abrir",
        "open_message": "Abrir documento",
        "save": "Guardar",
        "save_message": "Guardar documento",
        "save_as": "Guardar como",
        "save_as_message": "Guardar documento como",
        "print": "Imprimir",
        "print_message": "Imprimir documento",
        "find": "Buscar",
        "find_message": "Buscar texto",
        "replace": "Reemplazar",
        "replace_message": "Reemplazar texto",
        "undo": "Deshacer",
        "undo_message": "Deshacer última acción",
        "redo": "Rehacer",
        "redo_message": "Rehacer última acción",
        "right": "Derecha",
        "right_message": "Alinear texto a la derecha",
        "center": "Centro",
        "center_message": "Alinear texto al centro",
        "left": "Izquierda",
        "left_message": "Alinear texto a la izquierda",
        "justify": "Justificar",
        "justify_message": "Justificar texto",
        "font": "Fuente",
        "font_message": "Cambiar fuente",
        "font_size": "Tamaño de fuente",
        "font_size_message": "Cambiar tamaño de fuente",
        "font_color": "Color de fuente",
        "font_color_message": "Cambiar color de fuente",
        "contentBackgroundColor": "Color de fondo",
        "contentBackgroundColor_message": "Cambiar color de fondo",
        "bold": "Negrita",
        "bold_message": "Texto en negrita",
        "italic": "Cursiva",
        "italic_message": "Texto en cursiva",
        "underline": "Subrayado",
        "underline_message": "Texto subrayado",
        "inc_font_message": "Aumentar tamaño de fuente",
        "dec_font_message": "Disminuir tamaño de fuente",
        "image": "Imagen",
        "image_message": "Insertar imagen",
        "find": "Buscar",
        "replace": "Reemplazar",
        "find": "Buscar",
        "untitled": "Sin título",
        "statistic": "Estadísticas",
        "statistic_message_1": "Líneas: {0}",
        "statistic_message_2": "Palabras: {0}",
        "statistic_message_3": "Caracteres: {0}",
        "statistic_message_4": "Páginas: {0}",
        "analysis": "Análisis",
        "analysis_message_1": "Palabra promedio: {0}",
        "analysis_message_2": "Línea promedio: {0}",
        "analysis_message_3": "Mayúsculas: {0}",
        "analysis_message_4": "Minúsculas: {0}",
        "analysis_message_5": "Idioma: {0}",
        "exit": "Salir",
        "exit_message": "¿Estás seguro de que quieres salir?",
        "cancel": "Cancelar",
        "rsdoc": "Documento RichSpan",
        "connection_verified": "Conexión verificada",
        "connection_denied": "Conexión denegada",
        "welcome-title": "Bienvenido — RichSpan",
        "intro": "Inicia sesión o regístrate con una cuenta de <b>BG Ecosystem</b> para continuar.",
        "logout": "Cerrar sesión",
        "sync_settings": "Sincronizar ajustes",
        "wrong_password": "Contraseña incorrecta",
        "no_account": "No tienes una cuenta.",
        "email": "Correo electrónico",
        "password": "Contraseña",
        "login": "Iniciar sesión",
        "register": "Registrarse",
        "error": "Error",
        "fill_all": "Por favor, rellene todos los campos.",
        "login_success": "Inicio de sesión correcto, redireccionando...",
        "wrong_credentials": "Credenciales incorrectas",
        "register_success": "Registro correcto, por favor inicie sesión.",
        "already_registered": "Ya registrado",
        "invalid_email": "Correo electrónico inválido",
        "bullet": "Viñeta",
        "numbered": "Numerado",
        "account": "Cuenta",
        "list": "Lista",
        "powersaver": "Ahorro de energía",
        "powersaver_message": "Ahorro de energía híbrido (Ultra/Estándar).",
    },
    "2052": {
        "new": "新建",
        "open": "打开",
        "save": "保存",
        "save_as": "另存为",
        "print": "打印",
        "exit": "退出",
        "file": "文件",
        "interface": "界面",
        "ui": "用户界面",
        "format": "格式",
        "alignment": "对齐",
        "color": "颜色",
        "multimedia": "多媒体",
        "darklight": "深色/浅色",
        "darklight_message": "更改主题",
        "edit": "编辑",
        "view": "查看",
        "viewmode": "视图模式",
        "viewmode_message": "更改视图模式",
        "help": "帮助",
        "help_message": "帮助",
        "help_shortcut": "快捷键",
        "help_description": "描述",
        "about": "关于",
        "new_message": "新建文档",
        "open_message": "打开文档",
        "save_message": "保存文档",
        "save_as_message": "另存为文档",
        "print_message": "打印文档",
        "find": "查找",
        "find_message": "查找文本",
        "replace": "替换",
        "replace_message": "替换文本",
        "undo": "撤销",
        "undo_message": "撤销操作",
        "redo": "重做",
        "redo_message": "重做操作",
        "right": "右对齐",
        "right_message": "右对齐文本",
        "center": "居中",
        "center_message": "居中文本",
        "left": "左对齐",
        "left_message": "左对齐文本",
        "justify": "对齐",
        "justify_message": "两端对齐文本",
        "font": "字体",
        "font_message": "更改字体",
        "font_size": "字体大小",
        "font_size_message": "更改字体大小",
        "font_color": "字体颜色",
        "font_color_message": "更改字体颜色",
        "contentBackgroundColor": "背景颜色",
        "contentBackgroundColor_message": "更改背景颜色",
        "bold": "粗体",
        "bold_message": "加粗文本",
        "italic": "斜体",
        "italic_message": "倾斜文本",
        "underline": "下划线",
        "underline_message": "文本下划线",
        "inc_font_message": "增大字体大小",
        "dec_font_message": "减小字体大小",
        "image": "图片",
        "image_message": "插入图片",
        "untitled": "未命名",
        "statistic": "统计",
        "statistic_message_1": "行数: {0}",
        "statistic_message_2": "字数: {0}",
        "statistic_message_3": "字符数: {0}",
        "statistic_message_4": "页数: {0}",
        "analysis": "分析",
        "analysis_message_1": "平均单词: {0}",
        "analysis_message_2": "平均行: {0}",
        "analysis_message_3": "大写字母: {0}",
        "analysis_message_4": "小写字母: {0}",
        "analysis_message_5": "语言: {0}",
        "exit_message": "您确定要退出吗？",
        "cancel": "取消",
        "rsdoc": "RichSpan 文档",
        "connection_verified": "连接已验证",
        "connection_denied": "连接被拒绝",
        "logout": "注销",
        "sync_settings": "同步设置",
        "welcome-title": "欢迎 — RichSpan",
        "intro": "使用 <b>BG 生态系统</b> 账户登录或注册以继续。",
        "wrong_password": "密码错误",
        "no_account": "您没有账户。",
        "email": "电子邮件",
        "password": "密码",
        "login": "登录",
        "register": "注册",
        "error": "错误",
        "fill_all": "请填写所有字段。",
        "login_success": "登录成功，正在重定向...",
        "wrong_credentials": "凭证错误",
        "register_success": "注册成功，请登录。",
        "already_registered": "已经注册",
        "invalid_email": "无效的电子邮件",
        "bullet": "项目符号",
        "numbered": "编号",
        "account": "账户",
        "list": "列表",
        "powersaver": "节能",
        "powersaver_message": "混合（超高效/标准）节能",
    },
    "1042": {
        "new": "새로 만들기",
        "open": "열기",
        "save": "저장",
        "save_as": "다른 이름으로 저장",
        "print": "인쇄",
        "exit": "종료",
        "file": "파일",
        "interface": "인터페이스",
        "ui": "UI",
        "format": "형식",
        "alignment": "정렬",
        "color": "색상",
        "multimedia": "멀티미디어",
        "darklight": "어두운/밝은 모드",
        "darklight_message": "테마 변경",
        "edit": "편집",
        "view": "보기",
        "viewmode": "보기 모드",
        "viewmode_message": "보기 모드 변경",
        "help": "도움말",
        "help_message": "도움말",
        "help_shortcut": "단축키",
        "help_description": "설명",
        "about": "정보",
        "new_message": "새 문서",
        "open_message": "문서 열기",
        "save_message": "문서 저장",
        "save_as_message": "문서를 다른 이름으로 저장",
        "print_message": "문서 인쇄",
        "find": "찾기",
        "find_message": "텍스트 찾기",
        "replace": "바꾸기",
        "replace_message": "텍스트 바꾸기",
        "undo": "실행 취소",
        "undo_message": "작업 취소",
        "redo": "다시 실행",
        "redo_message": "작업 다시 실행",
        "right": "오른쪽",
        "right_message": "텍스트 오른쪽 정렬",
        "center": "가운데",
        "center_message": "텍스트 가운데 정렬",
        "left": "왼쪽",
        "left_message": "텍스트 왼쪽 정렬",
        "justify": "양쪽 맞춤",
        "justify_message": "텍스트 양쪽 맞춤",
        "font": "글꼴",
        "font_message": "글꼴 변경",
        "font_size": "글꼴 크기",
        "font_size_message": "글꼴 크기 변경",
        "font_color": "글꼴 색상",
        "font_color_message": "글꼴 색상 변경",
        "contentBackgroundColor": "배경 색상",
        "contentBackgroundColor_message": "배경 색상 변경",
        "bold": "굵게",
        "bold_message": "굵게 텍스트",
        "italic": "기울임꼴",
        "italic_message": "기울임꼴 텍스트",
        "underline": "밑줄",
        "underline_message": "밑줄 텍스트",
        "inc_font_message": "글꼴 크기 증가",
        "dec_font_message": "글꼴 크기 감소",
        "image": "이미지",
        "image_message": "이미지 삽입",
        "untitled": "제목 없음",
        "statistic": "통계",
        "statistic_message_1": "줄: {0}",
        "statistic_message_2": "단어: {0}",
        "statistic_message_3": "문자: {0}",
        "statistic_message_4": "페이지: {0}",
        "analysis": "분석",
        "analysis_message_1": "평균 단어 길이: {0}",
        "analysis_message_2": "평균 줄 길이: {0}",
        "analysis_message_3": "대문자: {0}",
        "analysis_message_4": "소문자: {0}",
        "analysis_message_5": "언어: {0}",
        "exit_message": "정말로 종료하시겠습니까?",
        "cancel": "취소",
        "rsdoc": "RichSpan 문서",
        "connection_verified": "연결 확인됨",
        "connection_denied": "연결 거부됨",
        "logout": "로그아웃",
        "sync_settings": "설정 동기화",
        "welcome-title": "환영합니다 — RichSpan",
        "intro": "계속하려면 <b>BG Ecosystem</b> 계정으로 로그인하거나 등록하십시오.",
        "wrong_password": "잘못된 비밀번호",
        "no_account": "계정이 없습니다.",
        "email": "이메일",
        "password": "비밀번호",
        "login": "로그인",
        "register": "등록",
        "error": "오류",
        "fill_all": "모든 필드를 작성해 주세요.",
        "login_success": "로그인 성공, 리디렉션 중...",
        "wrong_credentials": "잘못된 자격 증명",
        "register_success": "등록 성공, 로그인해 주세요.",
        "already_registered": "이미 등록됨",
        "invalid_email": "잘못된 이메일",
        "bullet": "글머리 기호",
        "numbered": "번호 매기기",
        "account": "계정",
        "list": "목록",
        "powersaver": "전력 절약",
        "powersaver_message": "하이브리드 (울트라/표준) 전력 절약",
    },
    "1041": {
        "new": "新規",
        "open": "開く",
        "save": "保存",
        "save_as": "名前を付けて保存",
        "print": "印刷",
        "exit": "終了",
        "file": "ファイル",
        "interface": "インターフェース",
        "ui": "UI",
        "format": "フォーマット",
        "alignment": "整列",
        "color": "カラー",
        "multimedia": "マルチメディア",
        "darklight": "ダーク/ライト",
        "darklight_message": "テーマを変更",
        "edit": "編集",
        "view": "表示",
        "viewmode": "表示モード",
        "viewmode_message": "表示モードを変更",
        "help": "ヘルプ",
        "help_message": "ヘルプ",
        "help_shortcut": "ショートカット",
        "help_description": "説明",
        "about": "について",
        "new_message": "新しい文書",
        "open_message": "文書を開く",
        "save_message": "文書を保存",
        "save_as_message": "文書を別名で保存",
        "print_message": "文書を印刷",
        "find": "検索",
        "find_message": "テキストを検索",
        "replace": "置換",
        "replace_message": "テキストを置換",
        "undo": "元に戻す",
        "undo_message": "操作を元に戻す",
        "redo": "やり直し",
        "redo_message": "操作をやり直し",
        "right": "右",
        "right_message": "テキストを右揃え",
        "center": "中央",
        "center_message": "テキストを中央揃え",
        "left": "左",
        "left_message": "テキストを左揃え",
        "justify": "両端揃え",
        "justify_message": "テキストを両端揃え",
        "font": "フォント",
        "font_message": "フォントを変更",
        "font_size": "フォントサイズ",
        "font_size_message": "フォントサイズを変更",
        "font_color": "フォントカラー",
        "font_color_message": "フォントカラーを変更",
        "contentBackgroundColor": "背景色",
        "contentBackgroundColor_message": "背景色を変更",
        "bold": "太字",
        "bold_message": "テキストを太字に",
        "italic": "斜体",
        "italic_message": "テキストを斜体に",
        "underline": "下線",
        "underline_message": "テキストに下線を引く",
        "inc_font_message": "フォントサイズを増加",
        "dec_font_message": "フォントサイズを減少",
        "image": "画像",
        "image_message": "画像を挿入",
        "untitled": "無題",
        "statistic": "統計",
        "statistic_message_1": "行数: {0}",
        "statistic_message_2": "単語数: {0}",
        "statistic_message_3": "文字数: {0}",
        "statistic_message_4": "ページ数: {0}",
        "analysis": "分析",
        "analysis_message_1": "平均単語数: {0}",
        "analysis_message_2": "平均行数: {0}",
        "analysis_message_3": "大文字: {0}",
        "analysis_message_4": "小文字: {0}",
        "analysis_message_5": "言語: {0}",
        "exit_message": "本当に終了しますか？",
        "cancel": "キャンセル",
        "rsdoc": "RichSpan ドキュメント",
        "connection_verified": "接続確認済み",
        "connection_denied": "接続拒否",
        "logout": "ログアウト",
        "sync_settings": "設定を同期",
        "welcome-title": "ようこそ — RichSpan",
        "intro": "<b>BG Ecosystem</b> アカウントでログインまたは登録して続行してください。",
        "wrong_password": "パスワードが間違っています",
        "no_account": "アカウントがありません。",
        "email": "メール",
        "password": "パスワード",
        "login": "ログイン",
        "register": "登録",
        "error": "エラー",
        "fill_all": "すべてのフィールドを入力してください。",
        "login_success": "ログイン成功、リダイレクト中...",
        "wrong_credentials": "認証情報が間違っています",
        "register_success": "登録成功、ログインしてください。",
        "already_registered": "すでに登録済み",
        "invalid_email": "無効なメール",
        "bullet": "箇条書き",
        "numbered": "番号付き",
        "account": "アカウント",
        "list": "リスト",
        "powersaver": "省エネルギー",
        "powersaver_message": "ハイブリッド（ウルトラ/スタンダード）省エネルギー",
    },
    "1025": {
        "new": "جديد",
        "open": "فتح",
        "save": "حفظ",
        "save_as": "حفظ باسم",
        "print": "طباعة",
        "exit": "خروج",
        "file": "ملف",
        "interface": "واجهة",
        "ui": "واجهة المستخدم",
        "format": "تنسيق",
        "alignment": "محاذاة",
        "color": "لون",
        "multimedia": "وسائط متعددة",
        "darklight": "داكن/فاتح",
        "darklight_message": "تغيير السمة",
        "edit": "تعديل",
        "view": "عرض",
        "viewmode": "وضع العرض",
        "viewmode_message": "تغيير وضع العرض",
        "help": "مساعدة",
        "help_message": "مساعدة",
        "help_shortcut": "اختصارات",
        "help_description": "وصف",
        "about": "حول",
        "new_message": "مستند جديد",
        "open_message": "فتح مستند",
        "save_message": "حفظ المستند",
        "save_as_message": "حفظ المستند باسم",
        "print_message": "طباعة المستند",
        "find": "بحث",
        "find_message": "البحث عن نص",
        "replace": "استبدال",
        "replace_message": "استبدال النص",
        "undo": "تراجع",
        "undo_message": "تراجع عن الإجراء",
        "redo": "إعادة",
        "redo_message": "إعادة الإجراء",
        "right": "محاذاة لليمين",
        "right_message": "محاذاة النص لليمين",
        "center": "توسيط",
        "center_message": "توسيط النص",
        "left": "محاذاة لليسار",
        "left_message": "محاذاة النص لليسار",
        "justify": "توزيع",
        "justify_message": "توزيع النص",
        "font": "خط",
        "font_message": "تغيير الخط",
        "font_size": "حجم الخط",
        "font_size_message": "تغيير حجم الخط",
        "font_color": "لون الخط",
        "font_color_message": "تغيير لون الخط",
        "contentBackgroundColor": "لون الخلفية",
        "contentBackgroundColor_message": "تغيير لون الخلفية",
        "bold": "عريض",
        "bold_message": "نص عريض",
        "italic": "مائل",
        "italic_message": "نص مائل",
        "underline": "تسطير",
        "underline_message": "تسطير النص",
        "inc_font_message": "زيادة حجم الخط",
        "dec_font_message": "تقليل حجم الخط",
        "image": "صورة",
        "image_message": "إدراج صورة",
        "untitled": "بدون عنوان",
        "statistic": "إحصائيات",
        "statistic_message_1": "الأسطر: {0}",
        "statistic_message_2": "الكلمات: {0}",
        "statistic_message_3": "الأحرف: {0}",
        "statistic_message_4": "الصفحات: {0}",
        "analysis": "تحليل",
        "analysis_message_1": "متوسط الكلمات: {0}",
        "analysis_message_2": "متوسط الأسطر: {0}",
        "analysis_message_3": "الحروف الكبيرة: {0}",
        "analysis_message_4": "الحروف الصغيرة: {0}",
        "analysis_message_5": "لغة: {0}",
        "exit_message": "هل أنت متأكد أنك تريد الخروج؟",
        "cancel": "إلغاء",
        "rsdoc": "مستند RichSpan",
        "connection_verified": "تم التحقق من الاتصال",
        "connection_denied": "تم رفض الاتصال",
        "logout": "تسجيل الخروج",
        "sync_settings": "مزامنة الإعدادات",
        "welcome-title": "مرحبا — RichSpan",
        "intro": "سجل الدخول أو قم بالتسجيل باستخدام حساب <b>BG Ecosystem</b> للمتابعة.",
        "wrong_password": "كلمة مرور خاطئة",
        "no_account": "لا تملك حسابًا.",
        "email": "البريد الإلكتروني",
        "password": "كلمة المرور",
        "login": "تسجيل الدخول",
        "register": "تسجيل",
        "error": "خطأ",
        "fill_all": "يرجى ملء جميع الحقول.",
        "login_success": "تم تسجيل الدخول بنجاح، جاري إعادة التوجيه...",
        "wrong_credentials": "بيانات الاعتماد خاطئة",
        "register_success": "تم التسجيل بنجاح، يرجى تسجيل الدخول.",
        "already_registered": "مسجل بالفعل",
        "invalid_email": "البريد الإلكتروني غير صالح",
        "bullet": "نقطة",
        "numbered": "مرقم",
        "account": "حساب",
        "list": "قائمة",
        "powersaver": "توفير الطاقة",
        "powersaver_message": "توفير الطاقة الهجين (ألترا/قياسي)",
    },
    "1091": {
        "new": "Yangi",
        "open": "Ochish",
        "save": "Saqlash",
        "save_as": "Saqlash sifatida",
        "print": "Chop etish",
        "exit": "Chiqish",
        "file": "Fayl",
        "interface": "Interfeys",
        "ui": "UI",
        "format": "Format",
        "alignment": "Tenglashtirish",
        "color": "Rang",
        "multimedia": "Ko'p vositalar",
        "darklight": "Qora/Oq",
        "darklight_message": "Tema o'zgartirish",
        "edit": "Tahrirlash",
        "view": "Ko'rinish",
        "viewmode": "Ko'rinish rejimi",
        "viewmode_message": "Ko'rinish rejimini o'zgartirish",
        "help": "Yordam",
        "help_message": "Yordam",
        "help_shortcut": "Qisqa tugmalar",
        "help_description": "Tavsif",
        "about": "Haqida",
        "new_message": "Yangi hujjat",
        "open_message": "Hujjatni ochish",
        "save_message": "Hujjatni saqlash",
        "save_as_message": "Hujjatni saqlash sifatida",
        "print_message": "Hujjatni chop etish",
        "find": "Topish",
        "find_message": "Matnni topish",
        "replace": "O'zgartirish",
        "replace_message": "Matnni o'zgartirish",
        "undo": "Qaytarish",
        "undo_message": "Harakatni qaytarish",
        "redo": "Qayta bajarish",
        "redo_message": "Harakatni qayta bajarish",
        "right": "O'ngga",
        "right_message": "Matnni o'ngga tenglashtirish",
        "center": "Markazlashtirish",
        "center_message": "Matnni markazlashtirish",
        "left": "Chapga",
        "left_message": "Matnni chapga tenglashtirish",
        "justify": "Tenglashtirish",
        "justify_message": "Matnni tenglashtirish",
        "font": "Shrift",
        "font_message": "Shriftni o'zgartirish",
        "font_size": "Shrift o'lchami",
        "font_size_message": "Shrift o'lchamini o'zgartirish",
        "font_color": "Shrift rangi",
        "font_color_message": "Shrift rangini o'zgartirish",
        "contentBackgroundColor": "Fon rangi",
        "contentBackgroundColor_message": "Fon rangini o'zgartirish",
        "bold": "Qalin",
        "bold_message": "Matnni qalin qilish",
        "italic": "Yam-yashil",
        "italic_message": "Matnni yam-yashil qilish",
        "underline": "Tagdan chizish",
        "underline_message": "Matnni tagdan chizish",
        "inc_font_message": "Shrift o'lchamini oshirish",
        "dec_font_message": "Shrift o'lchamini kamaytirish",
        "image": "Rasm",
        "image_message": "Rasm qo'shish",
        "untitled": "Sarlavhasiz",
        "statistic": "Statistika",
        "statistic_message_1": "Qatorlar: {0}",
        "statistic_message_2": "So'zlar: {0}",
        "statistic_message_3": "Belgilar: {0}",
        "statistic_message_4": "Sahifalar: {0}",
        "analysis": "Tahlil",
        "analysis_message_1": "O'rtacha so'z: {0}",
        "analysis_message_2": "O'rtacha qator: {0}",
        "analysis_message_3": "Katta harf: {0}",
        "analysis_message_4": "Kichik harf: {0}",
        "analysis_message_5": "Til: {0}",
        "exit_message": "Chiqishni xohlayotganingizga ishonchingiz komilmi?",
        "cancel": "Bekor qilish",
        "rsdoc": "RichSpan hujjati",
        "connection_verified": "Ulanish tasdiqlangan",
        "connection_denied": "Ulanish rad etildi",
        "logout": "Chiqish",
        "sync_settings": "Sozlamalarni sinxronlashtirish",
        "welcome-title": "Xush kelibsiz — RichSpan",
        "intro": "<b>BG Ecosystem</b> hisobingiz bilan kirish yoki ro'yxatdan o'tish orqali davom eting.",
        "wrong_password": "Noto'g'ri parol",
        "no_account": "Hisobingiz mavjud emas.",
        "email": "Elektron pochta",
        "password": "Parol",
        "login": "Kirish",
        "register": "Ro'yxatdan o'tish",
        "error": "Xato",
        "fill_all": "Iltimos, barcha maydonlarni to'ldiring.",
        "login_success": "Kirish muvaffaqiyatli, yo'naltirilmoqda...",
        "wrong_credentials": "Noto'g'ri ma'lumotlar",
        "register_success": "Ro'yxatdan o'tish muvaffaqiyatli, iltimos kirish.",
        "already_registered": "Allaqachon ro'yxatdan o'tgan",
        "invalid_email": "Noto'g'ri elektron pochta",
        "bullet": "Nuqtali",
        "numbered": "Raqamlangan",
        "account": "Hisob",
        "list": "Ro'yxat",
        "powersaver": "Quvvat tejash",
        "powersaver_message": "Gibrid (Ultra/Standart) quvvat tejash.",
    },
    "1049": {
        "new": "Новый",
        "open": "Открыть",
        "save": "Сохранить",
        "save_as": "Сохранить как",
        "print": "Печать",
        "exit": "Выход",
        "file": "Файл",
        "interface": "Интерфейс",
        "ui": "UI",
        "format": "Формат",
        "alignment": "Выравнивание",
        "color": "Цвет",
        "multimedia": "Мультимедиа",
        "darklight": "Темная/Светлая",
        "darklight_message": "Изменить тему",
        "edit": "Правка",
        "view": "Просмотр",
        "viewmode": "Режим просмотра",
        "viewmode_message": "Изменить режим просмотра",
        "help": "Помощь",
        "help_message": "Помощь",
        "help_shortcut": "Ярлыки",
        "help_description": "Описание",
        "about": "О программе",
        "new_message": "Новый документ",
        "open_message": "Открыть документ",
        "save_message": "Сохранить документ",
        "save_as_message": "Сохранить документ как",
        "print_message": "Распечатать документ",
        "find": "Найти",
        "find_message": "Найти текст",
        "replace": "Заменить",
        "replace_message": "Заменить текст",
        "undo": "Отменить",
        "undo_message": "Отменить действие",
        "redo": "Повторить",
        "redo_message": "Повторить действие",
        "right": "По правому краю",
        "right_message": "Выравнить текст по правому краю",
        "center": "По центру",
        "center_message": "Выравнить текст по центру",
        "left": "По левому краю",
        "left_message": "Выравнить текст по левому краю",
        "justify": "По ширине",
        "justify_message": "Выравнить текст по ширине",
        "font": "Шрифт",
        "font_message": "Изменить шрифт",
        "font_size": "Размер шрифта",
        "font_size_message": "Изменить размер шрифта",
        "font_color": "Цвет шрифта",
        "font_color_message": "Изменить цвет шрифта",
        "contentBackgroundColor": "Цвет фона",
        "contentBackgroundColor_message": "Изменить цвет фона",
        "bold": "Жирный",
        "bold_message": "Жирный текст",
        "italic": "Курсив",
        "italic_message": "Курсивный текст",
        "underline": "Подчеркнутый",
        "underline_message": "Подчеркнутый текст",
        "inc_font_message": "Увеличить размер шрифта",
        "dec_font_message": "Уменьшить размер шрифта",
        "image": "Изображение",
        "image_message": "Вставить изображение",
        "untitled": "Без названия",
        "statistic": "Статистика",
        "statistic_message_1": "Строки: {0}",
        "statistic_message_2": "Слова: {0}",
        "statistic_message_3": "Символы: {0}",
        "statistic_message_4": "Страницы: {0}",
        "analysis": "Анализ",
        "analysis_message_1": "Среднее слово: {0}",
        "analysis_message_2": "Средняя строка: {0}",
        "analysis_message_3": "Заглавные: {0}",
        "analysis_message_4": "Строчные: {0}",
        "analysis_message_5": "Язык: {0}",
        "exit_message": "Вы уверены, что хотите выйти?",
        "cancel": "Отмена",
        "rsdoc": "RichSpan Документ",
        "connection_verified": "Подключение проверено",
        "connection_denied": "Подключение отклонено",
        "logout": "Выход",
        "sync_settings": "Синхронизировать настройки",
        "welcome-title": "Добро пожаловать — RichSpan",
        "intro": "Войдите или зарегистрируйтесь с помощью аккаунта <b>BG Ecosystem</b>, чтобы продолжить.",
        "wrong_password": "Неправильный пароль",
        "no_account": "У вас нет аккаунта.",
        "email": "Электронная почта",
        "password": "Пароль",
        "login": "Войти",
        "register": "Зарегистрироваться",
        "error": "Ошибка",
        "fill_all": "Пожалуйста, заполните все поля.",
        "login_success": "Вход выполнен успешно, перенаправление...",
        "wrong_credentials": "Неправильные учетные данные",
        "register_success": "Регистрация успешна, пожалуйста, войдите.",
        "already_registered": "Уже зарегистрирован",
        "invalid_email": "Неверный email",
        "bullet": "Метка",
        "numbered": "Нумерованный",
        "account": "Аккаунт",
        "list": "Список",
        "powersaver": "Энергосбережение",
        "powersaver_message": "Гибридное (Ультра/Стандартное) энергосбережение.",
    },
    "1036": {
        "new": "Nouveau",
        "open": "Ouvrir",
        "save": "Enregistrer",
        "save_as": "Enregistrer sous",
        "print": "Imprimer",
        "exit": "Quitter",
        "file": "Fichier",
        "interface": "Interface",
        "ui": "UI",
        "format": "Format",
        "alignment": "Alignement",
        "color": "Couleur",
        "multimedia": "Multimédia",
        "darklight": "Sombre/Clair",
        "darklight_message": "Changer le thème",
        "edit": "Éditer",
        "view": "Afficher",
        "viewmode": "Mode d'affichage",
        "viewmode_message": "Changer le mode d'affichage",
        "help": "Aide",
        "help_message": "Aide",
        "help_shortcut": "Raccourcis",
        "help_description": "Description",
        "about": "À propos",
        "new_message": "Nouveau document",
        "open_message": "Ouvrir le document",
        "save_message": "Enregistrer le document",
        "save_as_message": "Enregistrer le document sous",
        "print_message": "Imprimer le document",
        "find": "Trouver",
        "find_message": "Trouver du texte",
        "replace": "Remplacer",
        "replace_message": "Remplacer le texte",
        "undo": "Annuler",
        "undo_message": "Annuler l'action",
        "redo": "Rétablir",
        "redo_message": "Rétablir l'action",
        "right": "Droite",
        "right_message": "Aligner le texte à droite",
        "center": "Centre",
        "center_message": "Aligner le texte au centre",
        "left": "Gauche",
        "left_message": "Aligner le texte à gauche",
        "justify": "Justifier",
        "justify_message": "Justifier le texte",
        "font": "Police",
        "font_message": "Changer la police",
        "font_size": "Taille de police",
        "font_size_message": "Changer la taille de la police",
        "font_color": "Couleur de la police",
        "font_color_message": "Changer la couleur de la police",
        "contentBackgroundColor": "Couleur de fond",
        "contentBackgroundColor_message": "Changer la couleur de fond",
        "bold": "Gras",
        "bold_message": "Texte en gras",
        "italic": "Italique",
        "italic_message": "Texte en italique",
        "underline": "Souligné",
        "underline_message": "Texte souligné",
        "inc_font_message": "Augmenter la taille de la police",
        "dec_font_message": "Diminuer la taille de la police",
        "image": "Image",
        "image_message": "Insérer une image",
        "untitled": "Sans titre",
        "statistic": "Statistique",
        "statistic_message_1": "Lignes : {0}",
        "statistic_message_2": "Mots : {0}",
        "statistic_message_3": "Caractères : {0}",
        "statistic_message_4": "Pages : {0}",
        "analysis": "Analyse",
        "analysis_message_1": "Moyenne des mots : {0}",
        "analysis_message_2": "Moyenne des lignes : {0}",
        "analysis_message_3": "Majuscules : {0}",
        "analysis_message_4": "Minuscules : {0}",
        "analysis_message_5": "Langue : {0}",
        "exit_message": "Êtes-vous sûr de vouloir quitter ?",
        "cancel": "Annuler",
        "rsdoc": "Document RichSpan",
        "connection_verified": "Connexion vérifiée",
        "connection_denied": "Connexion refusée",
        "logout": "Déconnexion",
        "sync_settings": "Synchroniser les paramètres",
        "welcome-title": "Bienvenue — RichSpan",
        "intro": "Connectez-vous ou inscrivez-vous avec un compte <b>BG Ecosystem</b> pour continuer.",
        "wrong_password": "Mot de passe incorrect",
        "no_account": "Vous n'avez pas de compte.",
        "email": "Email",
        "password": "Mot de passe",
        "login": "Connexion",
        "register": "Inscription",
        "error": "Erreur",
        "fill_all": "Veuillez remplir tous les champs.",
        "login_success": "Connexion réussie, redirection...",
        "wrong_credentials": "Identifiants incorrects",
        "register_success": "Inscription réussie, veuillez vous connecter.",
        "already_registered": "Déjà inscrit",
        "invalid_email": "Email invalide",
        "bullet": "Puces",
        "numbered": "Numéroté",
        "account": "Compte",
        "list": "Liste",
        "powersaver": "Économie d'énergie",
        "powersaver_message": "Économie d'énergie hybride (Ultra/Standard).",
    },
    "1032": {
        "new": "Νέο",
        "open": "Άνοιγμα",
        "save": "Αποθήκευση",
        "save_as": "Αποθήκευση ως",
        "print": "Εκτύπωση",
        "exit": "Έξοδος",
        "file": "Αρχείο",
        "interface": "Διεπαφή",
        "ui": "UI",
        "format": "Μορφοποίηση",
        "alignment": "Στοίχιση",
        "color": "Χρώμα",
        "multimedia": "Πολυμέσα",
        "darklight": "Σκοτεινό/Ανοιχτό",
        "darklight_message": "Αλλαγή θέματος",
        "edit": "Επεξεργασία",
        "view": "Προβολή",
        "viewmode": "Λειτουργία προβολής",
        "viewmode_message": "Αλλαγή λειτουργίας προβολής",
        "help": "Βοήθεια",
        "help_message": "Βοήθεια",
        "help_shortcut": "Συντομεύσεις",
        "help_description": "Περιγραφή",
        "about": "Σχετικά",
        "new_message": "Νέο έγγραφο",
        "open_message": "Άνοιγμα εγγράφου",
        "save_message": "Αποθήκευση εγγράφου",
        "save_as_message": "Αποθήκευση εγγράφου ως",
        "print_message": "Εκτύπωση εγγράφου",
        "find": "Εύρεση",
        "find_message": "Εύρεση κειμένου",
        "replace": "Αντικατάσταση",
        "replace_message": "Αντικατάσταση κειμένου",
        "undo": "Αναίρεση",
        "undo_message": "Αναίρεση ενέργειας",
        "redo": "Επαναφορά",
        "redo_message": "Επαναφορά ενέργειας",
        "right": "Δεξιά",
        "right_message": "Στοίχιση κειμένου δεξιά",
        "center": "Κέντρο",
        "center_message": "Στοίχιση κειμένου στο κέντρο",
        "left": "Αριστερά",
        "left_message": "Στοίχιση κειμένου αριστερά",
        "justify": "Δικαιολογημένο",
        "justify_message": "Δικαιολόγηση κειμένου",
        "font": "Γραμματοσειρά",
        "font_message": "Αλλαγή γραμματοσειράς",
        "font_size": "Μέγεθος γραμματοσειράς",
        "font_size_message": "Αλλαγή μεγέθους γραμματοσειράς",
        "font_color": "Χρώμα γραμματοσειράς",
        "font_color_message": "Αλλαγή χρώματος γραμματοσειράς",
        "contentBackgroundColor": "Χρώμα φόντου",
        "contentBackgroundColor_message": "Αλλαγή χρώματος φόντου",
        "bold": "Έντονα",
        "bold_message": "Έντονο κείμενο",
        "italic": "Πλάγια",
        "italic_message": "Πλάγιο κείμενο",
        "underline": "Υπογραμμισμένο",
        "underline_message": "Υπογραμμισμένο κείμενο",
        "inc_font_message": "Αύξηση μεγέθους γραμματοσειράς",
        "dec_font_message": "Μείωση μεγέθους γραμματοσειράς",
        "image": "Εικόνα",
        "image_message": "Εισαγωγή εικόνας",
        "untitled": "Αχωρίστως",
        "statistic": "Στατιστικά",
        "statistic_message_1": "Γραμμές: {0}",
        "statistic_message_2": "Λέξεις: {0}",
        "statistic_message_3": "Χαρακτήρες: {0}",
        "statistic_message_4": "Σελίδες: {0}",
        "analysis": "Ανάλυση",
        "analysis_message_1": "Μέσος όρος λέξεων: {0}",
        "analysis_message_2": "Μέσος όρος γραμμών: {0}",
        "analysis_message_3": "Κεφαλαία: {0}",
        "analysis_message_4": "Μικρά: {0}",
        "analysis_message_5": "Γλώσσα: {0}",
        "exit_message": "Είστε σίγουροι ότι θέλετε να βγείτε;",
        "cancel": "Ακύρωση",
        "rsdoc": "Έγγραφο RichSpan",
        "connection_verified": "Σύνδεση επιβεβαιωμένη",
        "connection_denied": "Σύνδεση απορρίφθηκε",
        "logout": "Αποσύνδεση",
        "sync_settings": "Συγχρονισμός ρυθμίσεων",
        "welcome-title": "Καλώς ήρθατε — RichSpan",
        "intro": "Συνδεθείτε ή εγγραφείτε με τον λογαριασμό <b>BG Ecosystem</b> για να συνεχίσετε.",
        "wrong_password": "Λάθος κωδικός",
        "no_account": "Δεν έχετε λογαριασμό.",
        "email": "Email",
        "password": "Κωδικός",
        "login": "Σύνδεση",
        "register": "Εγγραφή",
        "error": "Σφάλμα",
        "fill_all": "Παρακαλώ συμπληρώστε όλα τα πεδία.",
        "login_success": "Σύνδεση επιτυχής, ανακατεύθυνση...",
        "wrong_credentials": "Λάθος στοιχεία",
        "register_success": "Η εγγραφή ήταν επιτυχής, παρακαλώ συνδεθείτε.",
        "already_registered": "Ήδη εγγεγραμμένος",
        "invalid_email": "Μη έγκυρο email",
        "bullet": "Κουκίδα",
        "numbered": "Αριθμημένος",
        "account": "Λογαριασμός",
        "list": "Λίστα",
        "powersaver": "Εξοικονόμηση ενέργειας",
        "powersaver_message": "Υβριδική (Ultra/Κανονική) εξοικονόμηση ενέργειας.",
    },
}
